# Generated by Django 5.0.3 on 2024-03-11 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(default=0)),
                ('id', models.IntegerField(default=0)),
                ('success', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'PAYMENTS',
            },
        ),
        migrations.CreateModel(
            name='Premium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(default=0)),
                ('unix_time', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'PREMIUM',
            },
        ),
    ]
