import sys
sys.path.append('../')
# for i in dbhandle.get_tables():
#     print(i)
#     dbhandle.execute_sql(f'ALTER TABLE "{i}" ADD UNIQUE (chat_id);')
pdbhandle.execute_sql('ALTER TABLE "PREMIUM" ADD UNIQUE(uid);')
pdbhandle.execute_sql('ALTER TABLE "BONUS" ADD UNIQUE(chat_id);')
pdbhandle.execute_sql('ALTER TABLE "SETTINGS" ADD UNIQUE(chat_id);')
pdbhandle.execute_sql('ALTER TABLE "JoinedDate" ADD UNIQUE(chat_id);')
pdbhandle.execute_sql('ALTER TABLE "USER_JOINED_DATE" ADD UNIQUE(uid);')
pdbhandle.execute_sql('ALTER TABLE "LVL" ADD UNIQUE(uid);')
pdbhandle.execute_sql('ALTER TABLE "PREMMENU" ADD UNIQUE(uid);')
pdbhandle.execute_sql('ALTER TABLE "PREFIXES" ADD UNIQUE(chat_id);')
pdbhandle.execute_sql('ALTER TABLE "ACCESS_NAMES" ADD UNIQUE(chat_id);')
pdbhandle.execute_sql('ALTER TABLE "CHATLIMIT" ADD UNIQUE(id);')
pdbhandle.execute_sql('ALTER TABLE "PAYMENTS" ADD UNIQUE(uid);')
pdbhandle.execute_sql('ALTER TABLE "CMDNAMES" ADD UNIQUE(uid);')
pdbhandle.execute_sql('ALTER TABLE "DUELWINS" ADD UNIQUE(uid);')
pdbhandle.execute_sql('ALTER TABLE "LASTFIVECOMMANDS" ADD UNIQUE(uid);')
pdbhandle.execute_sql('ALTER TABLE "GLOBALWARNS" ADD UNIQUE(uid);')
pdbhandle.execute_sql('ALTER TABLE "REPORTS" ADD UNIQUE(uid);')
pdbhandle.execute_sql('ALTER TABLE "REPORTANSWERS" ADD UNIQUE(report_text);')
pdbhandle.execute_sql('ALTER TABLE "COMMENTS" ADD UNIQUE(uid);')
pdbhandle.execute_sql('ALTER TABLE "LIKES" ADD UNIQUE(uid);')
pdbhandle.execute_sql('ALTER TABLE "INFBANNED" ADD UNIQUE(uid);')
pdbhandle.execute_sql('ALTER TABLE "LEAVEDCHATS" ADD UNIQUE(id);')
pdbhandle.execute_sql('ALTER TABLE "REWARDS" ADD UNIQUE(uid);')
pdbhandle.execute_sql('ALTER TABLE "COMPLETEDREWARDS" ADD UNIQUE(uid);')
pdbhandle.execute_sql('ALTER TABLE "NOTIFICATIONS" ADD UNIQUE(chat_id);')
pdbhandle.execute_sql('ALTER TABLE "TYPEQUEUE" ADD UNIQUE(chat_id);')
pdbhandle.execute_sql('ALTER TABLE "REPORTWARNS" ADD UNIQUE(uid);')
pdbhandle.execute_sql('ALTER TABLE "MUTEDUSERS" ADD UNIQUE(uid);')
pdbhandle.execute_sql('ALTER TABLE "REBOOTS" ADD UNIQUE(chat_id);')
